### ISSUE TITLE
Wrong description in PowerShell Gallery

### ISSUE THREAD

**Issue by markwragg** [OneLogicalMyth/PowerShell-HipChat#1]
I noticed today while publishing my own HipChat module to the PowerShell gallery that yours has the description "A simple module that takes pipeline input from a CSV file and returns warranty information" which I think has been accidentally duplicated from the other module you published.

https://www.powershellgallery.com/packages/HipChat/1.0

**Comment by OneLogicalMyth** [comment]
Hi thanks for spotting this will get it updated soon as possible. :)
